### ISSUE TITLE
Implementing Tags for Posts

### ISSUE THREAD

**Issue by ewright516** [staten-island-tech/vue-project-2-edwin-and-thomas-and-n-i-k-i-t-a-daniel#13]
Using [WikiMedia Rest Api](https://m.mediawiki.org/wiki/API:REST_API), allow users to tag their posts with certain tags depending on what they’re reviewing. Also allow users to search using tags

**Comment by ewright516** [comment]
yeah, no. wikimedia not happening, users can create their own searchable tags when creating the post

**Comment by DPustobayev** [comment]
did we not finish this yet?

**Comment by ewright516** [comment]
> did we not finish this yet?

I finished the tags but it's just not pulled from the api. Still searchable

**Comment by DPustobayev** [comment]
> > did we not finish this yet?
> 
> I finished the tags but it's just not pulled from the api. Still searchable
ok then sir
