### ISSUE TITLE
Create avatars using dicebear

### ISSUE THREAD

**Issue by DPustobayev** [staten-island-tech/vue-project-2-edwin-and-thomas-and-n-i-k-i-t-a-daniel#19]
Hey edwin what should the avatar style be?

**Comment by ewright516** [comment]
that’s on you bossman

**Comment by DPustobayev** [comment]
Ok, but if it looks ass i should not be blamed!

**Comment by ewright516** [comment]
you will be but that’s ok

**Comment by DPustobayev** [comment]
ok since you get emails and can access this, edwin when i create a new array property in the database is it automatically given to every user?

**Comment by ewright516** [comment]
if you create a new array property in the code on signup, it only adds it to users that sign up after the code is implemented. If that’s not what you’re talking about lmk

**Comment by DPustobayev** [comment]
so what i want to do is add a new property to every user just so they have their own profile picture and can later edit it. is there a way where i can add that property to every user at once?

**Comment by ewright516** [comment]
Get all the users, run an updatedoc thing in a foreach, delete the code for it after

**Comment by DPustobayev** [comment]
oh ok i thought firebase might do it itself, thank you!

**Comment by wrrius** [comment]
Made the picture property with an image source to do this. All that is left for pfp's is actually putting them somewhere and possible customization.

**Comment by DPustobayev** [comment]
Made the picture property with an image source to do this. All that is left for pfp's is actually putting them somewhere and possible customization.
